services:
  artifact-check:
    build: .
    container_name: artifact_check

  artifact-viewer:
    image: python:3.12-slim
    container_name: artifact-viewer
    working_dir: /data
    volumes:
      - ./artifact:/data
    command: python -m http.server 8000
    ports:
      - "8000:8000"